### PR TITLE
State creation

### PR DESCRIPTION
**Pull request by fcollman**
I think it's time to merge this thing!

### CODE REVIEW

**Comment by ceesem** [comment]
FYI, I removed all of the server stuff for the time being.

**Comment by ceesem** [comment]
But I agree, ready to merge if you guys think so!

**Comment by sdorkenw** [comment]
Great! The requirements are not up to date though. 
`dash` and `dashdataframe` are missing.

**Comment by fcollman** [comment]
those aren't strictly required, if you want to build an application that uses both the examples show you how, but this library stands alone.

**Comment by fcollman** [comment]
agreed about annotationframeworkclient though

**Pull request merged**
