### PR TITLE
Nglite integration

### PR DESCRIPTION
**Pull request by ceesem**
I just wanted to get this PR going. Given that the previous version definitely does not work right now (especially if a newer neuroglancer were installed), I'd also be happy to pull it and then fix bugs in main.

### CODE REVIEW

**Comment by fcollman** [comment]
the example did not work in this PR when i tried it..

**Comment by fcollman** [comment]
nevermind.. i had an installation issue.. the example works.

**Comment by fcollman** [comment]
Is this designed to only work with seung lab neuroglancer, or both?

**Comment by fcollman** [comment]
Can you add some maintenance documentation on the steps you think are needed to sync the nglite with an update to neuroglancer, or seung lab neuroglancer to maintain compatibility?

**Comment by ceesem** [comment]
There seems to be a breaking change in the states between new mainline Neuroglancer and the Seung lab branch. One of the goals of this new design was to give the possibility of loading different neuroglancer python modules for different target clients, but I haven’t started to implement the mainline version yet. I need to dive into the new mainline client to understand better what would need to happen, but I think it should be possible.

**Comment by fcollman** [comment]
that makes sense, I think adding some explicit statements in the readme that this is the current state (seung-lab branch only) and future vision would help people not get confused.

**Comment by fcollman** [comment]
I think other than the documentation changes I suggested this is good to go.

**Pull request merged**
